/** 实验页种子数据（含推荐引擎所需的硬门槛与检索字段） */
export const mockJobs = [
  {
    id: 1,
    organization: "山东大学",
    title: "2026年专职辅导员招聘公告",
    publishDate: "2026-05-15",
    deadline: "2026-05-24",
    category: "高校院所招聘",
    provinceCity: "山东·济南",
    slots: 15,
    majors: "不限专业，马克思主义理论类优先",
    ageRequirement: "28周岁以下",
    education: "硕士及以上",
    summary:
      "山东大学面向海内外招聘专职辅导员，纳入事业编制管理。须中共党员，具备学生工作经历，通过笔试、面试、心理测评。入职后驻学生宿舍值班。",
    content:
      "山东大学面向海内外招聘专职辅导员，纳入事业编制管理。须中共党员，具备学生工作经历，通过笔试、面试、心理测评。入职后驻学生宿舍值班。笔试内容包括公共基础知识与辅导员实务。",
    sourceUrl: "https://www.rsrczp.sdu.edu.cn/info/1047/6602.htm",
  },
  {
    id: 2,
    organization: "湖南省教育厅",
    title: "2026年省直事业单位集中公开招聘公告",
    publishDate: "2026-05-12",
    deadline: "2026-06-20",
    category: "地方编制求职",
    provinceCity: "湖南·长沙",
    slots: 42,
    majors: "财会、中文、法学、计算机等相关专业",
    ageRequirement: "35周岁以下，博士可放宽至40周岁",
    education: "本科及以上",
    summary:
      "省直事业单位统一笔试，考《职业能力倾向测验》与《综合应用能力》。部分岗位面向服务基层项目人员定向招聘。",
    content:
      "省直事业单位统一笔试，考《职业能力倾向测验》与《综合应用能力》。部分岗位面向服务基层项目人员定向招聘。报名采取网上报名方式，资格初审后缴费确认。",
    sourceUrl: "https://example.com/hunan-2026",
  },
  {
    id: 3,
    organization: "中国科学院某研究所",
    title: "2026年博士后招收简章（物理方向）",
    publishDate: "2026-05-10",
    deadline: "2026-05-22",
    category: "博士/申博/博后",
    provinceCity: "北京·海淀",
    slots: 6,
    majors: "凝聚态物理、光学、量子信息",
    ageRequirement: "获得博士学位3年内，一般不超过35周岁",
    education: "博士",
    summary:
      "提供有竞争力薪酬与科研启动经费，合作导师团队承担国家重大专项。需以第一作者发表高水平论文。",
    content:
      "提供有竞争力薪酬与科研启动经费，合作导师团队承担国家重大专项。需以第一作者发表高水平论文。博士后合作导师为院士团队，出站可推荐留所工作。",
    sourceUrl: "https://example.com/cas-postdoc",
  },
  {
    id: 4,
    organization: "武汉大学",
    title: "2026年非事业编制科研助理招聘",
    publishDate: "2026-05-08",
    deadline: "2026-07-08",
    category: "高校院所招聘",
    provinceCity: "湖北·武汉",
    slots: 3,
    majors: "生物学、药学、化学相关专业",
    ageRequirement: "30周岁以下",
    education: "硕士及以上",
    summary:
      "协助课题组完成实验、数据整理与项目管理，合同制聘用，表现优秀可推荐攻读博士。",
    content:
      "协助课题组完成实验、数据整理与项目管理，合同制聘用，表现优秀可推荐攻读博士。实验室位于武汉大学医学部，提供基本社保与绩效补贴。",
    sourceUrl: "https://example.com/whu-ra",
  },
  {
    id: 5,
    organization: "深圳市人力资源和社会保障局",
    title: "2026年事业单位公开招聘（教育类）",
    publishDate: "2026-05-06",
    deadline: "2026-05-21",
    category: "地方编制求职",
    provinceCity: "广东·深圳",
    slots: 28,
    majors: "教育学、学科教学、心理健康教育",
    ageRequirement: "本科30周岁、硕士35周岁以下",
    education: "本科及以上",
    summary:
      "深圳市教育局直属学校教师岗，纳入事业编制。须教师资格证，部分岗位限应届毕业生。",
    content:
      "深圳市教育局直属学校教师岗，纳入事业编制。须教师资格证，部分岗位限应届毕业生。面试采取试讲与结构化问答相结合方式进行。",
    sourceUrl: "https://example.com/sz-edu",
  },
  {
    id: 6,
    organization: "南京大学",
    title: "2026年申请考核制博士研究生招生简章",
    publishDate: "2026-05-04",
    deadline: "2026-08-31",
    category: "博士/申博/博后",
    provinceCity: "江苏·南京",
    slots: 120,
    majors: "详见招生目录，理工医文法多学科",
    ageRequirement: "硕士研究生毕业不超过5年",
    education: "硕士及以上",
    summary:
      "实行申请-考核制，综合材料评审与面试。外语须达到 CET-6 或同等水平，有核心期刊论文者优先。",
    content:
      "实行申请-考核制，综合材料评审与面试。外语须达到 CET-6 或同等水平，有核心期刊论文者优先。材料审核包括研究计划书、推荐信与科研成果证明。",
    sourceUrl: "https://example.com/nju-phd",
  },
  {
    id: 7,
    organization: "浙江大学医学院附属医院",
    title: "2026年临床医师招聘公告",
    publishDate: "2026-05-02",
    deadline: "2026-06-15",
    category: "高校院所招聘",
    provinceCity: "浙江·杭州",
    slots: 18,
    majors: "临床医学、口腔医学（规培方向）",
    ageRequirement: "博士35周岁、硕士30周岁以下",
    education: "硕士及以上",
    summary:
      "招聘规培合格或应届规培结业医师，部分岗位需执业医师资格证。提供住房补贴与科研启动金。",
    content:
      "招聘规培合格或应届规培结业医师，部分岗位需执业医师资格证。提供住房补贴与科研启动金。住院医师规范化培训合格证须在入职前取得。",
    sourceUrl: "https://example.com/zju-hospital",
  },
  {
    id: 8,
    organization: "成都市人社局",
    title: "2026年公开考试录用公务员公告",
    publishDate: "2026-04-28",
    deadline: "2026-05-23",
    category: "地方编制求职",
    provinceCity: "四川·成都",
    slots: 356,
    majors: "专业目录详见附件，法学财会计算机需求量大",
    ageRequirement: "18-35周岁（应届硕士可至40周岁）",
    education: "本科及以上",
    summary:
      "四川省公务员考试成都职位，笔试《行测》《申论》。公安、法院系统另加专业科目。",
    content:
      "四川省公务员考试成都职位，笔试《行测》《申论》。公安、法院系统另加专业科目。基层工作经历计算截止时间为报名首日。",
    sourceUrl: "https://example.com/chengdu-gwy",
  },
  {
    id: 9,
    organization: "复旦大学",
    title: "2026年管理助理及行政人员招聘",
    publishDate: "2026-04-25",
    deadline: "2026-06-01",
    category: "高校院所招聘",
    provinceCity: "上海",
    slots: 8,
    majors: "不限，文史哲法经管类优先",
    ageRequirement: "32周岁以下",
    education: "本科及以上",
    summary:
      "学校机关及二级单位行政岗，劳务派遣或校聘合同。要求熟练使用办公软件，有高校行政经验优先。",
    content:
      "学校机关及二级单位行政岗，劳务派遣或校聘合同。要求熟练使用办公软件，有高校行政经验优先。岗位职责包括文稿起草、会务协调与档案管理。",
    sourceUrl: "https://example.com/fudan-admin",
  },
  {
    id: 10,
    organization: "厦门大学",
    title: "2026年博士后科学基金获得者支持计划",
    publishDate: "2026-04-20",
    deadline: "2026-07-20",
    category: "博士/申博/博后",
    provinceCity: "福建·厦门",
    slots: 20,
    majors: "海洋科学、经济学、化学、计算机",
    ageRequirement: "博士毕业2年内，不超过35周岁",
    education: "博士",
    summary:
      "配套福建省博士后科研资助，鼓励交叉学科研究。出站后可申请留校任教或推荐至合作单位。",
    content:
      "配套福建省博士后科研资助，鼓励交叉学科研究。出站后可申请留校任教或推荐至合作单位。进站须全职，不得兼职从事其他有薪酬工作。",
    sourceUrl: "https://example.com/xmu-postdoc",
  },
];

export const EDUCATION_FILTER_OPTIONS = [
  "全部",
  "大专",
  "本科",
  "硕士",
  "博士",
];
